spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
        url: ${DB_URL}
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        properties:
            hibernate:
                format_sql: true
        show-sql: true

jwt:
    secret: ${JWT_SECRET}
    lifetime: ${DB_LIFETIME}