version: "3.9"
services:
  skiron_app:
    image: pampero.registry.jetbrains.space/p/popper/skiron/skiron-app:latest
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME: ${JWT_LIFETIME}
    depends_on:
      - skiron_db
    ports:
      - "8008:8080"

  skiron_db:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA}
    volumes:
      - skiron-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  skiron-data: